### PR TITLE
build and publish linux/arm64 images in addition to linux/amd64

### PR DESCRIPTION
**Pull request by krancour**
Signed-off-by: Kent Rancourt <kent.rancourt@microsoft.com>

### CODE REVIEW

**Review by vdice — COMMENTED** [review]
It looks like the Dockerfile changes aren't included here... or am I missing something?

**Comment by krancour** [comment]
@vdice no Dockerfile changes required in this case.

**Comment by krancour** [comment]
To clarify, changes to the Dockerfile have only been needed in cases where we do a multistage build and in the first stage, prefer to cross-compile for the target architecture using a container on the native architecture-- because it's faster. Absent that concern, no Dockerfile changes are necessary.

**Review by vdice — APPROVED** [review]

**Pull request merged**
